import random
from datetime import datetime, timezone

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy import func
from sqlalchemy.orm import Session

from database import get_db
from models.quiz import QuizQuestion

router = APIRouter(prefix="/api/quiz", tags=["quiz"])

# ── Cricket question bank ─────────────────────────────────────────────────────
# difficulty: easy | medium | hard
_Q = [
    # ── Rules & basics ────────────────────────────────────────────────────────
    {"q": "How many players are in a cricket team?",
     "a": "11", "w": ["9", "10", "12"], "d": "easy"},
    {"q": "How many balls are bowled in a standard over?",
     "a": "6", "w": ["4", "5", "8"], "d": "easy"},
    {"q": "What is it called when a batsman scores zero runs?",
     "a": "A duck", "w": ["A blob", "A zero", "A goose"], "d": "easy"},
    {"q": "What does LBW stand for?",
     "a": "Leg Before Wicket", "w": ["Left Behind Wicket", "Leg By Wicket", "Long Before Wicket"], "d": "easy"},
    {"q": "How many stumps form a wicket?",
     "a": "3", "w": ["2", "4", "5"], "d": "easy"},
    {"q": "How many bails are placed on top of the stumps?",
     "a": "2", "w": ["1", "3", "4"], "d": "easy"},
    {"q": "What color ball is used in Test cricket?",
     "a": "Red", "w": ["White", "Pink", "Yellow"], "d": "easy"},
    {"q": "What color ball is used in most limited-overs cricket?",
     "a": "White", "w": ["Red", "Pink", "Blue"], "d": "easy"},
    {"q": "How many runs does a ball hit over the boundary without bouncing score?",
     "a": "6", "w": ["4", "5", "7"], "d": "easy"},
    {"q": "How many runs does a ball that crosses the boundary after bouncing score?",
     "a": "4", "w": ["2", "3", "6"], "d": "easy"},
    {"q": "Approximately how long is a cricket pitch?",
     "a": "22 yards (20.12 metres)", "w": ["18 yards", "25 yards", "30 yards"], "d": "easy"},
    {"q": "How many overs does each team face in an ODI?",
     "a": "50", "w": ["20", "40", "60"], "d": "easy"},
    {"q": "In T20 cricket, how many overs does each team bat?",
     "a": "20", "w": ["10", "15", "25"], "d": "easy"},
    {"q": "How many wickets can fall in a single cricket innings?",
     "a": "10", "w": ["9", "11", "7"], "d": "easy"},
    {"q": "What position stands behind the stumps to catch the ball?",
     "a": "Wicket-keeper", "w": ["Fine leg", "First slip", "Square leg"], "d": "easy"},
    {"q": "What is a 'wide' in cricket?",
     "a": "A delivery too far from the batsman to hit", "w": ["A ball that hits the stumps", "A ball that bounces twice", "A ball caught on the full"], "d": "easy"},
    {"q": "What is a 'no ball' in cricket?",
     "a": "An illegal delivery", "w": ["A missed shot", "A ball that goes for four", "A slow delivery"], "d": "easy"},
    {"q": "What is a score of 100 runs by a single batsman called?",
     "a": "A century", "w": ["A ton play", "A milestone", "A classic"], "d": "easy"},
    {"q": "What does 'run out' mean?",
     "a": "A batsman fails to make their ground while running between wickets",
     "w": ["The batting side scores all needed runs", "A batsman voluntarily leaves the crease", "The batting side runs out of overs"], "d": "easy"},
    {"q": "What is a 'bouncer' in cricket?",
     "a": "A short-pitched delivery that rises sharply towards the batsman",
     "w": ["A ball that hits the boundary", "A very slow loop delivery", "A full toss aimed at the body"], "d": "easy"},
    {"q": "What does 'declaring' mean in cricket?",
     "a": "A captain voluntarily ends their team's innings",
     "w": ["A bowler claims five wickets", "An umpire stops play early", "The batting side loses all wickets"], "d": "easy"},
    {"q": "What is a 'hat-trick' in cricket?",
     "a": "Three wickets in three consecutive balls",
     "w": ["Five wickets in an innings", "Two wickets off consecutive balls", "Four wickets in one over"], "d": "easy"},
    {"q": "What is the 'crease' in cricket?",
     "a": "Lines on the pitch marking safe areas for batsmen",
     "w": ["The seam on the cricket ball", "The stitching on batting gloves", "The center mark of the pitch"], "d": "easy"},
    {"q": "Which country is credited with inventing cricket?",
     "a": "England", "w": ["Australia", "India", "West Indies"], "d": "easy"},
    {"q": "What is a 'free hit' in limited-overs cricket?",
     "a": "A delivery after a no-ball where the batsman cannot be dismissed except by a run out",
     "w": ["A ball the fielding team bowls for free", "An extra delivery at the end of an over", "A penalty given for time-wasting"], "d": "easy"},

    # ── Formats & structure ────────────────────────────────────────────────────
    {"q": "What is the longest format of cricket?",
     "a": "Test cricket", "w": ["ODI", "T20", "T10"], "d": "easy"},
    {"q": "How many days can a Test match last?",
     "a": "5", "w": ["3", "4", "7"], "d": "easy"},
    {"q": "What color ball is used for day-night Test matches?",
     "a": "Pink", "w": ["Red", "White", "Orange"], "d": "medium"},
    {"q": "What is a 'powerplay' in limited-overs cricket?",
     "a": "A period when fielding restrictions reduce fielders outside the circle",
     "w": ["When the batting team accelerates their run rate", "A tactical time-out for each team", "When a bowler bowls consecutive overs"], "d": "medium"},
    {"q": "What is the DLS method used for?",
     "a": "Calculating revised targets in rain-interrupted matches",
     "w": ["Measuring pitch hardness", "Determining toss decisions", "Rating player performances"], "d": "medium"},
    {"q": "What does 'follow-on' mean in Test cricket?",
     "a": "The trailing team is made to bat again immediately after their first innings",
     "w": ["A bowler bowls two consecutive overs", "Batting in the final session of a day", "The fielding side chases a batsman"], "d": "medium"},
    {"q": "In a T20 match, what is the maximum number of overs one bowler can bowl?",
     "a": "4", "w": ["3", "5", "6"], "d": "medium"},
    {"q": "What is the 'Super Over' used for?",
     "a": "Breaking a tie at the end of a limited-overs match",
     "w": ["An extra over given for slow over rates", "A bonus over for the top-scoring team", "An extra over in powerplay"], "d": "medium"},

    # ── Bowling types ──────────────────────────────────────────────────────────
    {"q": "What is a 'googly'?",
     "a": "An off-break bowled with a leg-break action by a right-arm spinner",
     "w": ["A fast bouncer aimed at the body", "A slow looping full toss", "A deliberate wide bowled to unsettle the batsman"], "d": "medium"},
    {"q": "What is a 'yorker'?",
     "a": "A ball pitched near the batsman's feet at the crease",
     "w": ["A ball that rises sharply off the pitch", "A slow looping delivery", "A ball aimed at the body above the waist"], "d": "medium"},
    {"q": "What is 'leg spin'?",
     "a": "Spin that turns from leg to off side for a right-handed batsman",
     "w": ["Bowling with the non-dominant hand", "Spin aimed at the leg stump only", "A short-pitched spin delivery"], "d": "medium"},
    {"q": "What is a 'chinaman' delivery?",
     "a": "Left-arm unorthodox spin that turns away from a right-handed batsman",
     "w": ["A bouncer aimed at the head", "A deliberate no ball", "An off-break by a right-arm bowler"], "d": "hard"},
    {"q": "What is a 'doosra'?",
     "a": "An off-spinner's delivery that turns away from a right-handed batsman — the opposite of normal off-spin",
     "w": ["A leg-spinner's googly", "A fast short-pitched delivery", "A deliberate waist-high full toss"], "d": "hard"},
    {"q": "What is a 'beamer'?",
     "a": "A full-pitched delivery aimed above waist height at the batsman",
     "w": ["A spinning delivery with extra bounce", "A slow deceptive looping ball", "A short ball that skids low"], "d": "medium"},
    {"q": "What is 'reverse swing'?",
     "a": "When an old ball swings in the opposite direction to conventional swing",
     "w": ["Bowling with the left hand from around the wicket", "Batting from the reverse crease", "An off-spin delivery going the other way"], "d": "hard"},
    {"q": "What is a 'flipper' in cricket?",
     "a": "A leg-spin delivery that skids on quickly and stays low",
     "w": ["A top-spin delivery", "A slow looping googly", "A deliberate full toss by a spinner"], "d": "hard"},

    # ── Batting & fielding ─────────────────────────────────────────────────────
    {"q": "What is a 'cover drive'?",
     "a": "An attacking stroke played through the cover region on the off side",
     "w": ["A defensive shot played to the leg side", "A reverse sweep", "A lofted shot over the boundary"], "d": "medium"},
    {"q": "What is a 'sweep shot'?",
     "a": "A batting stroke played by kneeling and sweeping the ball to the leg side",
     "w": ["A shot played over the bowler's head", "A straight drive down the ground", "A cut shot played on the off side"], "d": "medium"},
    {"q": "What is a 'maiden over'?",
     "a": "An over in which no runs are scored off the bat",
     "w": ["An over with 6 sixes", "The first over of an innings", "An over in which a wicket falls"], "d": "medium"},
    {"q": "What is a 'slip cordon'?",
     "a": "Fielders positioned behind the batsman on the off side to catch edges",
     "w": ["A bowling technique for swing", "A batting stance adjustment", "Fielders arranged around the boundary"], "d": "medium"},
    {"q": "What is the fielding position 'mid-on'?",
     "a": "A fielder positioned on the on side roughly level with the bowler",
     "w": ["A fielder at the boundary on the off side", "A fielder directly behind the stumps", "A fielder at square on the leg side"], "d": "medium"},
    {"q": "What is a 'golden duck'?",
     "a": "Being dismissed for zero runs off the very first ball faced",
     "w": ["Scoring a century on debut", "Hitting a six off the first ball faced", "Not being dismissed in an entire Test series"], "d": "medium"},
    {"q": "What is 'batting average' in cricket?",
     "a": "Total runs scored divided by number of dismissals",
     "w": ["Runs scored per over", "Strike rate per 100 balls", "Total centuries divided by innings played"], "d": "medium"},
    {"q": "What is 'bowling average'?",
     "a": "Runs conceded per wicket taken",
     "w": ["Wickets taken per match", "Overs bowled per innings", "Balls bowled per run conceded"], "d": "medium"},
    {"q": "What fielding position is roughly at right angles to the batsman on the leg side?",
     "a": "Square leg", "w": ["Fine leg", "Mid-on", "Mid-wicket"], "d": "medium"},
    {"q": "What is 'caught behind'?",
     "a": "Dismissed when the wicket-keeper catches an edge off the bat",
     "w": ["A catch taken at the long-on boundary", "A catch at first slip", "A stumping off a wide delivery"], "d": "easy"},
    {"q": "What is a 'nurdle' in cricket?",
     "a": "A gentle deflection of the ball for a single or two",
     "w": ["A type of spin delivery", "A very slow bouncer", "A dismissal off a pad deflection"], "d": "hard"},

    # ── Famous players ────────────────────────────────────────────────────────
    {"q": "Which player holds the record for the most Test centuries?",
     "a": "Sachin Tendulkar (51)", "w": ["Ricky Ponting", "Brian Lara", "Jacques Kallis"], "d": "medium"},
    {"q": "Which player scored the highest individual innings in Test cricket — 400 not out?",
     "a": "Brian Lara", "w": ["Matthew Hayden", "Garfield Sobers", "Sachin Tendulkar"], "d": "medium"},
    {"q": "What is Sir Donald Bradman's legendary Test batting average?",
     "a": "99.94", "w": ["89.78", "95.50", "87.32"], "d": "medium"},
    {"q": "Who has taken the most wickets in Test cricket history?",
     "a": "Muttiah Muralitharan (800)", "w": ["Shane Warne", "James Anderson", "Glenn McGrath"], "d": "medium"},
    {"q": "What country does Sachin Tendulkar represent?",
     "a": "India", "w": ["Pakistan", "Sri Lanka", "Bangladesh"], "d": "easy"},
    {"q": "Who holds the record for the highest individual ODI score — 264 runs?",
     "a": "Rohit Sharma", "w": ["Martin Guptill", "Sachin Tendulkar", "Chris Gayle"], "d": "hard"},
    {"q": "Who scored the first double century (200+) in men's ODI cricket?",
     "a": "Sachin Tendulkar", "w": ["Rohit Sharma", "Martin Guptill", "Chris Gayle"], "d": "hard"},
    {"q": "How many Test wickets did Shane Warne take in his career?",
     "a": "708", "w": ["619", "750", "563"], "d": "hard"},
    {"q": "Which bowler is known as the 'Sultan of Swing'?",
     "a": "Wasim Akram", "w": ["Glenn McGrath", "Malcolm Marshall", "Joel Garner"], "d": "hard"},
    {"q": "Which cricketer is nicknamed 'The Don'?",
     "a": "Sir Donald Bradman", "w": ["Vivian Richards", "Ian Botham", "Garfield Sobers"], "d": "easy"},
    {"q": "Who is known as the 'Master Blaster' of cricket?",
     "a": "Sachin Tendulkar", "w": ["Brian Lara", "Viv Richards", "Chris Gayle"], "d": "easy"},
    {"q": "Who scored the most runs in ODI cricket history?",
     "a": "Sachin Tendulkar", "w": ["Ricky Ponting", "Kumar Sangakkara", "Virat Kohli"], "d": "medium"},

    # ── Tournaments & history ─────────────────────────────────────────────────
    {"q": "In which year was the first Men's Cricket World Cup held?",
     "a": "1975", "w": ["1965", "1983", "1992"], "d": "medium"},
    {"q": "Which country hosted the first Cricket World Cup in 1975?",
     "a": "England", "w": ["Australia", "West Indies", "India"], "d": "medium"},
    {"q": "Which country has won the most Men's ODI Cricket World Cups?",
     "a": "Australia (5)", "w": ["West Indies", "India", "England"], "d": "medium"},
    {"q": "In which year did India win their first Cricket World Cup?",
     "a": "1983", "w": ["1975", "1996", "2003"], "d": "medium"},
    {"q": "Which country won the inaugural ICC Men's T20 World Cup in 2007?",
     "a": "India", "w": ["Pakistan", "Australia", "South Africa"], "d": "medium"},
    {"q": "What is the 'Ashes' series?",
     "a": "A Test series between England and Australia",
     "w": ["Between India and Pakistan", "Between West Indies and South Africa", "Between New Zealand and Sri Lanka"], "d": "easy"},
    {"q": "What does the Ashes urn symbolize?",
     "a": "The death of English cricket after Australia's first win on English soil in 1882",
     "w": ["The burning of the first cricket bat", "The end of amateur cricket era", "The cremation of the first cricket pitch"], "d": "hard"},
    {"q": "Which stadium is known as 'The Home of Cricket'?",
     "a": "Lord's Cricket Ground, London", "w": ["The Oval, London", "Eden Gardens, Kolkata", "MCG, Melbourne"], "d": "medium"},
    {"q": "What is the MCG?",
     "a": "Melbourne Cricket Ground — one of the world's largest cricket stadiums",
     "w": ["Mumbai Cricket Ground", "Manchester Cricket Ground", "Mohali Cricket Ground"], "d": "medium"},
    {"q": "In which year was the first day-night Test match played?",
     "a": "2015 (Adelaide, Australia vs New Zealand)",
     "w": ["2010", "2007", "2019"], "d": "hard"},
    {"q": "Which country does the IPL (Indian Premier League) belong to?",
     "a": "India", "w": ["England", "Australia", "South Africa"], "d": "easy"},
    {"q": "What does ICC stand for?",
     "a": "International Cricket Council",
     "w": ["Indian Cricket Championship", "International Cricket Competition", "Innings Control Committee"], "d": "easy"},
    {"q": "What is the 'Big Bash League'?",
     "a": "Australia's domestic T20 competition",
     "w": ["India's domestic T20 competition", "England's T20 Blast league", "South Africa's T20 competition"], "d": "medium"},

    # ── Terminology & slang ────────────────────────────────────────────────────
    {"q": "What is a 'jaffa' in cricket slang?",
     "a": "An unplayable, exceptional delivery",
     "w": ["A very easy delivery to hit", "A fielding mistake", "An extra given by the umpire"], "d": "medium"},
    {"q": "What is 'Mankading'?",
     "a": "Running out the non-striker before delivering the ball",
     "w": ["Deliberate obstruction of the field", "A deliberate no ball", "A fake fielding attempt"], "d": "hard"},
    {"q": "What is the 'Decision Review System' (DRS)?",
     "a": "A technology system used by teams to review on-field umpire decisions",
     "w": ["A broadcast scoring system", "A pitch condition assessment tool", "A player fitness rating system"], "d": "medium"},
    {"q": "What is a 'sticky wicket'?",
     "a": "A damp or difficult pitch that makes batting very hard",
     "w": ["A very dry pitch that assists spin", "A pitch with uneven bounce", "A brand new pitch on Day 1"], "d": "medium"},
    {"q": "What is 'bowling a maiden'?",
     "a": "Bowling an over from which the batsman scores no runs",
     "w": ["Bowling out the first batsman of the innings", "Delivering the first over of the match", "Bowling out a batsman on debut"], "d": "medium"},
    {"q": "What does 'the corridor of uncertainty' mean?",
     "a": "The area just outside off stump where the batsman is unsure whether to play or leave",
     "w": ["A fielding zone near the boundary", "The area between the bowling crease and popping crease", "The zone a spinner targets on a turning pitch"], "d": "hard"},
    {"q": "What is a 'century partnership'?",
     "a": "When two batsmen together contribute 100 runs in a partnership",
     "w": ["When a bowler takes five wickets in a century match", "A 100-over game format", "When a team scores 100 runs in a single session"], "d": "medium"},

    # ── Fielding position visual questions ────────────────────────────────────────
    {"q": "What fielding position is marked on the field?",
     "a": "Wicket-keeper", "w": ["1st Slip", "Short Leg", "Fine Leg"], "d": "easy", "type": "field", "pos": "wicket-keeper"},
    {"q": "What fielding position is marked on the field?",
     "a": "1st Slip", "w": ["Wicket-keeper", "2nd Slip", "Gully"], "d": "easy", "type": "field", "pos": "1st-slip"},
    {"q": "What fielding position is marked on the field?",
     "a": "2nd Slip", "w": ["1st Slip", "Gully", "Third Man"], "d": "medium", "type": "field", "pos": "2nd-slip"},
    {"q": "What fielding position is marked on the field?",
     "a": "Gully", "w": ["Point", "2nd Slip", "Cover"], "d": "medium", "type": "field", "pos": "gully"},
    {"q": "What fielding position is marked on the field?",
     "a": "Point", "w": ["Gully", "Cover", "Square Leg"], "d": "easy", "type": "field", "pos": "point"},
    {"q": "What fielding position is marked on the field?",
     "a": "Cover", "w": ["Point", "Mid-off", "Mid-wicket"], "d": "medium", "type": "field", "pos": "cover"},
    {"q": "What fielding position is marked on the field?",
     "a": "Mid-off", "w": ["Mid-on", "Cover", "Long-off"], "d": "easy", "type": "field", "pos": "mid-off"},
    {"q": "What fielding position is marked on the field?",
     "a": "Long-off", "w": ["Long-on", "Mid-off", "Cover"], "d": "medium", "type": "field", "pos": "long-off"},
    {"q": "What fielding position is marked on the field?",
     "a": "Third Man", "w": ["Fine Leg", "2nd Slip", "Gully"], "d": "medium", "type": "field", "pos": "third-man"},
    {"q": "What fielding position is marked on the field?",
     "a": "Fine Leg", "w": ["Third Man", "Square Leg", "Mid-wicket"], "d": "easy", "type": "field", "pos": "fine-leg"},
    {"q": "What fielding position is marked on the field?",
     "a": "Square Leg", "w": ["Mid-wicket", "Fine Leg", "Mid-on"], "d": "easy", "type": "field", "pos": "square-leg"},
    {"q": "What fielding position is marked on the field?",
     "a": "Mid-wicket", "w": ["Square Leg", "Mid-on", "Cover"], "d": "medium", "type": "field", "pos": "mid-wicket"},
    {"q": "What fielding position is marked on the field?",
     "a": "Mid-on", "w": ["Mid-off", "Mid-wicket", "Long-on"], "d": "easy", "type": "field", "pos": "mid-on"},
    {"q": "What fielding position is marked on the field?",
     "a": "Long-on", "w": ["Long-off", "Mid-on", "Mid-wicket"], "d": "medium", "type": "field", "pos": "long-on"},
    {"q": "What fielding position is marked on the field?",
     "a": "Short Leg", "w": ["Wicket-keeper", "Square Leg", "1st Slip"], "d": "hard", "type": "field", "pos": "short-leg"},
]


def _seed_if_empty(db: Session):
    if db.query(QuizQuestion).count() > 0:
        return
    now = datetime.now(timezone.utc)
    for item in _Q:
        db.add(QuizQuestion(
            question=item["q"],
            correct_answer=item["a"],
            incorrect_answers=item["w"],
            difficulty=item["d"],
            category="Cricket",
            question_type=item.get("type", "text"),
            field_position=item.get("pos"),
            fetched_at=now,
        ))
    db.commit()


@router.get("/questions")
def get_questions(db: Session = Depends(get_db)):
    _seed_if_empty(db)
    qs = db.query(QuizQuestion).order_by(func.random()).limit(10).all()
    if not qs:
        raise HTTPException(status_code=503, detail="Quiz questions unavailable.")
    result = []
    for q in qs:
        options = list(q.incorrect_answers) + [q.correct_answer]
        random.shuffle(options)
        result.append({
            "id": q.id,
            "question": q.question,
            "options": options,
            "correct": q.correct_answer,
            "difficulty": q.difficulty or "medium",
            "category": q.category or "Cricket",
            "type": q.question_type or "text",
            "position": q.field_position,
        })
    return result
